globals:
  seed: 1213
  device: cuda
  num_epochs: 400
  ensemble: 0
  output_dir: ../user_data/20231211
  main_metric: epoch_accuracy
  minimize_metric: False
  input_key: image
  input_target_key: targets
  weights:
  folds:
    - 0

data:
  train_audio_path: ../user_data

dataset:
  name: NpyDataset
  sr: 48000
  img_size: 224
  params:
    n_mels: 128
    fmin: 20
    fmax: 16000

loss:
  name: CeLoss
  params:
    loss_type: ce

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: resnet34
  params:
#    pretrained: True
    pretrained: False
#    n_classes: 50

loader:
  train:
    batch_size: 64
    shuffle: True
    num_workers: 12
  valid:
    batch_size: 64
    shuffle: False
    num_workers: 12
  test:
    batch_size: 1
    shuffle: False
    num_workers: 1

callbacks:
  - name: AccCallback
    params:
      input_key: targets
      output_key: logits
      model_output_key: valance
      prefix: accuracy
#  - name: F1Callback
#    params:
##      input_key: targets
#      input_key: arousal_targets
#      output_key: logits
#      model_output_key: multiclass_proba
#      prefix: f1
#  - name: mAPCallback
#    params:
##      input_key: targets
#      input_key: arousal_targets
#      output_key: logits
#      model_output_key: multiclass_proba
#      prefix: mAP
